### ISSUE TITLE
Create new release with FASTA support?

### ISSUE THREAD

**Issue by rpetit3** [jimmyliu1326/SsuisSero#1]
Hello! 

Could you create a new release so that the Bioconda install has FASTA support?

Thank you!

**Comment by jimmyliu1326** [comment]
Sure can! Likely will get to it in a week or two.

**Comment by rpetit3** [comment]
Awesome! I can handle everything on the Bioconda side of things

**Comment by jimmyliu1326** [comment]
Oh in that case, I can create the release right away: [v1.0.1](https://github.com/jimmyliu1326/SsuisSero/releases/tag/v1.0.1) If you can update the bioconda recipe, that would be much appreciated 👍

**Comment by rpetit3** [comment]
Great! Bioconda Bot created the PR, I'll get it merged  https://github.com/bioconda/bioconda-recipes/pull/33251

Mind doing the same for https://github.com/jimmyliu1326/HpsuisSero?

**Comment by rpetit3** [comment]
Going to close this, thank you so much for the quick response!

**Comment by jimmyliu1326** [comment]
Sorry forgot to mention you will need to include flye in the `meta.yaml` btw

**Comment by rpetit3** [comment]
Will do no problem!
